### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by balan777** [jakevdp/PythonDataScienceHandbook#228]
Code does not work (ISBN 978-3-95845-696-9; Page 212): 

# Gesamte Datei in ein Python-Array einlesen
with open('recipeitems-latest.json', 'r') as f:
   # Die einzelnen Zeilen entnehmen
   data = (line.strip() for line in f)
   # Umformatierung der Zeilen als Listenelemente
   data_json = "[{0}]".format(','.join(data))
# Ergebnis als JSON einlesen
recipes = pd.read_json(data_json)
Traceback (most recent call last):

  File "<ipython-input-67-7332ec8c1e43>", line 6, in <module>
    data_json = "[{0}]".format(','.join(data))

  File "<ipython-input-67-7332ec8c1e43>", line 4, in <genexpr>
    data = (line.strip() for line in f)

  File "C:\Users\Willkommen\anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]

UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 3611: character maps to <undefined>

**Comment by balan777** [comment]
""" It works with encoding="utf8""""
import pandas as pd

with open('recipeitems-latest.json', 'r', encoding="utf8") as f:
    data = (line.strip() for line in f)
    data_json = "[{0}]".format(','.join(data))
recipes = pd.read_json(data_json)
