### ISSUE TITLE
Chanpter  03.11-Working-with-Time-Series 

### ISSUE THREAD

**Issue by Radar-Lei** [jakevdp/PythonDataScienceHandbook#94]
hi,jakevdp. I can't download the data using codes below:
**from pandas_datareader import data
goog = data.DataReader('GOOG', start='2004', end='2016',
                       data_source='google')**

goog = data.DataReader('GOOG', start='2004', end='2016',data_source='google')
Traceback (most recent call last):

  File "<ipython-input-15-8d3440448ab4>", line 1, in <module>
    goog = data.DataReader('GOOG', start='2004', end='2016',data_source='google')

  File "D:\Anaconda3\lib\site-packages\pandas_datareader\data.py", line 137, in DataReader
    session=session).read()

  File "D:\Anaconda3\lib\site-packages\pandas_datareader\base.py", line 181, in read
    params=self._get_params(self.symbols))

  File "D:\Anaconda3\lib\site-packages\pandas_datareader\base.py", line 79, in _read_one_data
    out = self._read_url_as_StringIO(url, params=params)

  File "D:\Anaconda3\lib\site-packages\pandas_datareader\base.py", line 90, in _read_url_as_StringIO
    response = self._get_response(url, params=params)

  File "D:\Anaconda3\lib\site-packages\pandas_datareader\base.py", line 126, in _get_response
    headers=headers)

  File "D:\Anaconda3\lib\site-packages\requests\sessions.py", line 531, in get
    return self.request('GET', url, **kwargs)

  File "D:\Anaconda3\lib\site-packages\requests\sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)

  File "D:\Anaconda3\lib\site-packages\requests\sessions.py", line 639, in send
    r = adapter.send(request, **kwargs)

  File "D:\Anaconda3\lib\site-packages\requests\adapters.py", line 502, in send
    raise ConnectionError(e, request=request)

ConnectionError: HTTPConnectionPool(host='www.google.com', port=80): Max retries exceeded with url: /finance/historical?q=GOOG&startdate=Jan+01%2C+2004&enddate=Jan+01%2C+2016&output=csv (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0000020DE647BFD0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))

**Comment by Radar-Lei** [comment]
and it works for me if the data is imported from Yahoo:
**goog = data.DataReader('F', start='2004', end='2016',data_source='yahoo')**

**Comment by lxneng** [comment]
@Radar-Lei  Maybe u should setup VPN first.

**Comment by Radar-Lei** [comment]
@lxneng yes, XD. But it seems only 251 records(from Google) are available in my case. Don't have any ideas right now .

![image](https://user-images.githubusercontent.com/29896531/30850427-18ed3600-a2d8-11e7-841d-e51374dc9968.png)
![image](https://user-images.githubusercontent.com/29896531/30850435-1cf1cd7e-a2d8-11e7-9003-c3f4518bb995.png)
![image](https://user-images.githubusercontent.com/29896531/30850441-2175b662-a2d8-11e7-9339-769ab41aac92.png)
